add

diff --git a/misc/iterm2.symlink/imgls b/misc/iterm2.symlink/imgls
--- a/misc/iterm2.symlink/imgls
+++ b/misc/iterm2.symlink/imgls
@@ -10,6 +10,13 @@ function print_osc() {
     fi
 }
 
+function check_dependency() {
+  if ! (builtin command -V "$1" > /dev/null 2>& 1); then
+    echo "imgcat: missing dependency: can't find $1" 1>& 2
+    exit 1
+  fi
+}
+
 # More of the tmux workaround described above.
 function print_st() {
     if [ x"$TERM" = "xscreen" ] ; then
@@ -50,10 +57,13 @@ function list_file() {
     echo -n "$dims "
     ls -ld "$fn"
   else
-    # ls -ld "$fn"
-    echo ""
+    ls -ld "$fn"
   fi
 }
+
+check_dependency php
+check_dependency base64
+check_dependency wc
 
 if [ $# -eq 0 ]; then
   for fn in *
